### ISSUE TITLE
Lot of stuff here that i didn't ask for

### ISSUE THREAD

**Issue by Gedgerl** [FreddieBrown/Bluefind#83]
>  Yeah it's a cool story bro but I don't remember asking for this in our last meeting

 -- George Edge, 2.4 k/d ratio on Call of Duty

>I still have a dream, a dream deeply rooted in the American dream – one day this nation will rise up and stop talking about things I didn't ask for, "We hold this dumb shit self evident: yet you still tell me about them." I have a dream...
 
 -- Martin Luther King

**Comment by walton98** [comment]
> UwU

-- Albert Einstein

Amen brother.

**Comment by FreddieBrown** [comment]
Duplicate issue, covered under #74
